required-players: 1
countdown-seconds: 10
lobby-spawn:
  world: 'world'
  x: -169.5
  y: 80.5
  z: -274.5
  yaw: 0
  pitch: 0

arenas:
  0:
    world: 'first'
    x: 0.5
    y: 4.5
    z: 0.5
    yaw: 180
    pitch: 0

  1:
    world: 'second'
    x: 0.5
    y: 4.5
    z: 0.5
    yaw: 180
    pitch: 0